# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_tuAomjK6nCrEF12F0epw-1XTp6AcFG
"""

pip install streamlit pandas

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Global Expansion Tracker", layout="wide")

@st.cache_data
def load_data():
    df = pd.read_csv("projects.csv")
    # Clean columns
    df["host_country"] = df["host_country"].astype(str).fillna("")
    df["sector"] = df["sector"].astype(str).fillna("")
    df["company_name"] = df["company_name"].astype(str).fillna("")
    return df

df = load_data()
df = df.dropna(subset=["host_country", "company_name"])

st.title("🌏 Chinese Companies’ Global Expansion Tracker")

# Sidebar filters
countries = st.sidebar.multiselect(
    "Select Host Country",
    sorted(df["host_country"].unique())
)
sectors = st.sidebar.multiselect(
    "Select Sector",
    sorted(df["sector"].unique())
)

# Apply filters
filtered = df.copy()
if countries:
    filtered = filtered[filtered["host_country"].isin(countries)]
if sectors:
    filtered = filtered[filtered["sector"].isin(sectors)]

# Summary metrics
st.subheader("Overview")
col1, col2 = st.columns(2)
col1.metric("Total Projects", len(filtered))
col2.metric("Unique Companies", filtered["company_name"].nunique())

# Table
st.subheader("Project Details")
st.dataframe(filtered)

# Chart
if len(filtered) > 0:
    fig = px.histogram(filtered, x="host_country", color="project_type", title="Projects by Country")
    st.plotly_chart(fig, use_container_width=True)
else:
    st.info("No projects found for the selected filters.")